spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: root
mybatis:
 mapper-locations: classpath*:mapper/*.xml
 configuration:
  map-underscore-to-camel-case: true
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #Redis
  redis:
    database: 0
    host: localhost
    port: 6379
  #es
  elasticsearch:
    uris: "localhost:9200"
    socket-timeout: "10s"
  #Rabbitmq
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    virtual-host: /
    port: 5672
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5
        acknowledge-mode: none
        default-requeue-rejected: true
    publisher-confirm-type: correlated
    publisher-returns: true

pagehelper:
  supportMethodsArguments: true
  helperDialect: mysql